server:
  port: 8090

spring:
  application:
    name: micro-service-eureka-peer1

security:
  basic:
    enabled: true

  user:
    name: admin
    password: admin

eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://admin:admin@localhost:8089/eureka/

